### ISSUE TITLE
Can't create more than max_prepared_stmt_count statements

### ISSUE THREAD

**Issue by yiming33** [vert-x3/vertx-mysql-postgresql-client#138]
![image](https://user-images.githubusercontent.com/19584310/51099421-85cca900-180b-11e9-9ffd-98c4ae841cc6.png)

Can’t create more than max_prepared_stmt_count statements

Why did Prepare not close?

**Comment by yiming33** [comment]
SQL connection should be closed every time

**Comment by yiming33** [comment]
@jponge @maeste @chirino @alexlehm

**Comment by yiming33** [comment]
@jponge @maeste @chirino @alexlehm need help

**Comment by codepitbull** [comment]
It's hard to tell without seeing your code.
Please share a reproducer.

**Comment by yiming33** [comment]
@codepitbull https://github.com/vert-x3/issues/issues/444

**Comment by yiming33** [comment]
> It's hard to tell without seeing your code.
> Please share a reproducer.

I submitted a new issue with a more detailed description.
https://github.com/vert-x3/issues/issues/444
