### ISSUE TITLE
Library style transaction syntax

### ISSUE THREAD

**Issue by gemmell** [vert-x3/vertx-mysql-postgresql-client#14]
This syntax is quite nice for transactions, any chance of supporting it?
https://github.com/mauricio/postgresql-async#transactions
```  
val future = connection.inTransaction {
    // stuff in transaction
    // more stuff in transaction.
  }
```

**Comment by Narigo** [comment]
When we get Scala support from code generation in Vert.x directly, you will get methods returning `Future[X]` which you can then use in for-comprehensions. You could write a wrapper around it then to enable such a syntax, but I don't think this can be an automatic process during code generation.

If you think something like this is possible, feel free to join the vertx-dev mailing list and have a look for the threads about Scala support :)

Thanks for your suggestion though :)
