### ISSUE TITLE
Missing Jasync documentation

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-mysql-postgresql-client#140]
Currently there is no specific doc for Jasync (i;e it's still the mauricio's one).

So it cannot be set on the web-site.

We need the actual doc to be tuned so it explains the difference with Mauricio's driver and give specific details about the implementation so we can use it properly on web-site docs.

**Comment by vietj** [comment]
assigned to you @codepitbull , feel free to get somebody contribute it :-)

**Comment by oshai** [comment]
I created a PR #141 for the asciidoc file. Is this the right place? Is there any other place to update?
