### ISSUE TITLE
Java 9+ support

### ISSUE THREAD

**Issue by salmonb** [vert-x3/vertx-mysql-postgresql-client#145]
I'm trying to migrate a Vert.x application accessing a Postgresql database using vertx-mysql-postgresql-client to Java 9+, but I'm getting this error on jvm start:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for C:\Users\Bruno\.m2\repository\com\github\mauricio\postgresql-async_2.12\0.2.21\postgresql-async_2.12-0.2.21.jar
Caused by: java.lang.IllegalArgumentException: postgresql.async.2.12: Invalid module name: '2' is not a Java identifier
```
It seems the problem comes from the postgresql-async_2.12 dependency which is not Java 9+ compliant (the automatic module name derived from the artifactId is not valid due to the presence of isolated digits).

I'm posting the issue here as the postgresql-async project has a notice saying it is not being maintained anymore.

Any plan to solve this issue?

**Comment by oshai** [comment]
I would recommend to try and move to jasync-sql flavor. It doesn't suffer from that issue.

**Comment by salmonb** [comment]
Good news :-) I hadn't noticed that move on the readme indeed... I changed vertx-mysql-postgresql-client to vertx-mysql-postgresql-client-jasync in my pom.xml and it works now. Thank you!
