### ISSUE TITLE
All the result of SQLRowStream run in a loop

### ISSUE THREAD

**Issue by okou19900722** [vert-x3/vertx-mysql-postgresql-client#148]
https://github.com/vert-x3/vertx-mysql-postgresql-client/blob/cbdbf729ad327834211140112b7958807a449650/vertx-mysql-postgresql-client-jasync/src/main/java/io/vertx/ext/asyncsql/impl/AsyncSQLRowStream.java#L69-L74

https://github.com/vert-x3/vertx-mysql-postgresql-client/blob/cbdbf729ad327834211140112b7958807a449650/vertx-mysql-postgresql-client-jasync/src/main/java/io/vertx/ext/asyncsql/impl/AsyncSQLRowStream.java#L93-L96

it will fetch all the result and never pause until it's finish

**Comment by okou19900722** [comment]
`128` is the default limit of fetch  in `vertx-jdbc-client`

https://github.com/vert-x3/vertx-jdbc-client/blob/cd3d609236c485221e79021df7a41b885d66af6f/src/main/java/io/vertx/ext/jdbc/impl/actions/StreamQuery.java#L36

**Comment by oshai** [comment]
In the driver itself, there is no such concept of `FETCH_SIZE`. Instead, all results are read to memory before future completes (or callback is called). So the parameter has no real effect as far as I know.

**Comment by okou19900722** [comment]
but it will block the event loop

**Comment by oshai** [comment]
do you mean that user code will block the event loop?

**Comment by okou19900722** [comment]
one million row will fetch in a loop, it's will block the event loop. I can only manually pause, and wait for 1 millisecond before resume

**Comment by oshai** [comment]
Another alternative is to schedule it later (manually) with delay. However, I am not sure there is an actual performance impact on blocking the event loop with cpu bound work. Usually, servers are io bound and not cpu bound and the pool of threads for events loop is of the size of the number of cores.

**Comment by vietj** [comment]
if you are using Postgres have you tried using the Reactive PG Client that provides a similar concept using cursor ?

**Comment by okou19900722** [comment]
I'm working with mysql. Looking forward to `vertx-sql-client`
