### ISSUE TITLE
How to switch driver between scala and kotlin version?

### ISSUE THREAD

**Issue by iseki0** [vert-x3/vertx-mysql-postgresql-client#150]
Sorry, I 'm the beginner. I want to use the new version driver because I need `maxWaitQueueSize` parameter.  
The dependency in my gradle file:
```
compile 'io.vertx:vertx-mysql-postgresql-client:3.6.3'
```
I know this question may be stupid. But I can't search for answer.    
Thank you.

**Comment by oshai** [comment]
Basically you need to replace artifact id to: `vertx-mysql-postgresql-client-jasync` and then change package names as explained here: https://github.com/jasync-sql/jasync-sql/wiki/Mauricio-Driver-Migration

**Comment by okou19900722** [comment]
Now, you may see three library named like `vertx-mysql-postgresql-client`:
* `vertx-mysql-postgresql-client`
* `vertx-mysql-postgresql-client-scala`
* `vertx-mysql-postgresql-client-jasync`,

`vertx-mysql-postgresql-client-scala` is basing on `vertx-mysql-postgresql-client`. It's easy to use by scala programer. but the driver of `vertx-mysql-postgresql-client` was not maintenanced.

the driver of `vertx-mysql-postgresql-client-jasync` is a new, community-active library.

but this repository was removed in vert.x 4.0. if you are using Postgres have you tried using the [Reactive PG Client](https://github.com/reactiverse/reactive-pg-client/). A [Mysql supported](https://github.com/reactiverse/reactive-pg-client/tree/mysql_support) branch is working in process.And a other library named `vertx-sql-client` is planing

**Comment by iseki0** [comment]
@okou19900722
@oshai
Thank you. I will have a look.
