### ISSUE TITLE
SQLConnection.commit()/rollback() causes WARNING: there is already a transaction in progress

### ISSUE THREAD

**Issue by lukeworthtkbt** [vert-x3/vertx-mysql-postgresql-client#16]
The implementation of `commit()`:

    override def commit(handler: Handler[AsyncResult[Void]]): SQLConnection = {
      if (inTransaction) {
        inTransaction = false
        connection.sendQuery("COMMIT") flatMap (_ => connection.sendQuery("BEGIN")) onComplete doneVoid(handler)
      } else {
        handler.handle(VFuture.failedFuture("Not in a transaction currently"))
      }
      this
    }

I believe the problem is that `inTransaction` remains `false` after the connection sends a `BEGIN` to the database, which messes up the behaviour of `beginTransactionIfNeeded` and `close`, etc. Same problem exists in `rollback`

**Comment by Narigo** [comment]
Could you tell me when this happens / show me a reproducer for this warning?
I've tried to set up a test that did multiple insert+commits on a connection with `setAutoCommit` set to `false`, but that didn't really echoed this error.

Thanks!

**Comment by lukeworthtkbt** [comment]
Sure. This code:
```
      AsyncSQLClient postgreSQLClient = PostgreSQLClient.createNonShared(vertx, postgreSQLClientConfig);
      postgreSQLClient.getConnection(connectionAsyncResult -> {
         SQLConnection connection = connectionAsyncResult.result();
         connection.setAutoCommit(false, voidAsyncResult -> {
            connection.query("SELECT 1", resultSetAsyncResult -> {
               connection.commit(voidAsyncResult1 -> {
                  connection.query("SELECT 2", resultSetAsyncResult1 -> {
                     connection.commit(voidAsyncResult2 -> {
                        connection.close(voidAsyncResult3 -> {

                        });
                     });
                  });
               });
            });
         });
      });
```
Produces this log output in postgres with `-d 2`:
```
LOG:  statement: BEGIN
LOG:  statement: SELECT 1
LOG:  statement: COMMIT
LOG:  statement: BEGIN
LOG:  statement: BEGIN
WARNING:  there is already a transaction in progress
LOG:  statement: SELECT 2
LOG:  statement: COMMIT
LOG:  statement: BEGIN
```

**Comment by Narigo** [comment]
Too slow, Mr. Fox ;)
Am 09.06.2015 08:08 schrieb "Tim Fox" <notifications@github.com>:
