### ISSUE TITLE
Relationship with vertx-sql-client

### ISSUE THREAD

**Issue by javenwang** [vert-x3/vertx-mysql-postgresql-client#160]
Hi, there is another sql client [eclipse-vertx/vertx-sql-client](https://github.com/eclipse-vertx/vertx-sql-client). So which one is more official? What is the relationship between these two?

**Comment by okou19900722** [comment]
`vertx-sql-client` is a new library, and `vertx-mysql-postgresql-client` has been removed in version 4.0. Currently only fix bugs .

欢迎加入vertx中国用户组讨论vertx的问题，qq群：515203212
