### ISSUE TITLE
Row.getBigDecimal() and getLocalTime() on MySQL

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-mysql-postgresql-client#169]
The MySQLRowImpl doesn't support getBigDecimal() (the natural Java mapping for SQL DECIMAL or NUMERIC) nor getLocalTime() (the natural mapping for TIME).

Reported in https://github.com/smallrye/smallrye-reactive-utils/issues/105.

**Comment by BillyYccc** [comment]
closed due to this is an issue for https://github.com/eclipse-vertx/vertx-sql-client.
