### ISSUE TITLE
PostgreSQL client should recognize ? placemarkers

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-mysql-postgresql-client#170]
Postgres' $1, $2, etc, is nonstandard, AFAIK, and contrary to ODBC and JDBC.

We should at least have the option to use this syntax if we want to.

Issue reported in https://github.com/smallrye/smallrye-reactive-utils/issues/106

**Comment by BillyYccc** [comment]
closed due to this is an issue for https://github.com/eclipse-vertx/vertx-sql-client.
