### ISSUE TITLE
Row.getXxxxx(alias) returns null when alias is uppercase

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-mysql-postgresql-client#171]
On Postgres, column aliases are converted to lowercase internally in the RowIterator, but the key passed to the getXxxxx() methods are not.

Issue reported in: https://github.com/smallrye/smallrye-reactive-utils/issues/104.

**Comment by BillyYccc** [comment]
closed due to this is an issue for https://github.com/eclipse-vertx/vertx-sql-client.
