### ISSUE TITLE
Pool is not thread safe

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-mysql-postgresql-client#20]
I was just looking at the Scala code for the pool, and my knowledge of Scala is poor, but it looks to me that the pool is not thread safe.

**Comment by purplefox** [comment]
@Narigo

**Comment by Narigo** [comment]
Can you share an asynchronous object pool which I could use then? I will most probably get it wrong if it's not working like this. I'd need it for the port to Java anyways then. Sorry for not being able to get this done before 3.0 :(
