### ISSUE TITLE
Any updates when this version hits the same version as the Vert.x modules?

### ISSUE THREAD

**Issue by marsbergen** [vert-x3/vertx-mysql-postgresql-client#28]

**Comment by Narigo** [comment]
Sorry for the late response @marsbergen 

We found a resolution to the blocking issues and we should be able to get this into a release cycle very soon, thanks to the extremely responsive and fast @vietj :)

**Comment by pmlopes** [comment]
It is available:

http://repo1.maven.org/maven2/io/vertx/vertx-mysql-postgresql-client/3.2.0/
