### ISSUE TITLE
Connection Pool is not releasing idle connections

### ISSUE THREAD

**Issue by Zwergal** [vert-x3/vertx-mysql-postgresql-client#33]
It seems like the driver opens connections until `maxPoolSize` is reached but never close a connection. So when the `maxPoolSize` is 10 I get 10 open connections which are all idle when nothing is using the application. I think the driver/module should release unused connection, so the Database-Server doesn't have tons of open idle connections.

 I'm using PostgreSQL btw.

**Comment by pmlopes** [comment]
@Zwergal could you provide a simple test case to show the problem? it would help us troubleshoot and locate the problem!

**Comment by purplefox** [comment]
I think that closing connections is something that's typically configured in the database itself (i.e. the database closes connections when they're idle)

**Comment by Zwergal** [comment]
As far as I know PostgreSQL can't do that automatically. You can do it with a cronjob which periodically terminates idle connections or use a connection pooler like pgBouncer. (See http://stackoverflow.com/questions/13236160/is-there-a-timeout-for-idle-postgresql-connections)

So I'm curious now what the best solution for this problem would be. Should the driver/module do this internally or should we use a solution like described above (pgBouncer, cronjob)?

**Comment by pmlopes** [comment]
maybe consider using the drivers internal pool instead of this?

**Comment by notsyncing** [comment]
I also encountered this situation, where the closed connections are idle in PostgreSQL, then the following DROP DATABASE will fail with "There are N other sessions using the database."
Maybe a function to clear the connection pool could be provided?

**Comment by xiaobaojiang** [comment]
@Zwergal 
```
As far as I know PostgreSQL can't do that automatically.
```
I think , vertx-mysql-postgresql-client provide the connection pool , and alse manage the  connetion close.
