### ISSUE TITLE
org.joda.time.DateTime

### ISSUE THREAD

**Issue by augeneinblick** [vert-x3/vertx-mysql-postgresql-client#34]
#4 fixes the case for (postgresql) column type "timestamp **without** time zone", but not for type "timestamp **with** time zone". Manually tested with current version 3.2.0.

"timestamp with time zone" leads to org.joda.time.DateTime which is not supported in _io.vertx.core.json.impl.Json.checkAndCopy_.

I'm a vertx-newb so perhaps i'm getting something wrong. If not i would be happy to be able to contribute a small patch :).

**Comment by Narigo** [comment]
@augeneinblick Can you give me an example on what exactly is wrong here? Could you maybe add a test that validates the issue?

**Comment by Narigo** [comment]
I guess giving me a code snippet on how you use it, would suffice. :)

**Comment by augeneinblick** [comment]
I forked and added a testcase which fails due the bug i meant above (sorry for missing creating a branch):
[testcase](https://github.com/augeneinblick/vertx-mysql-postgresql-client/commit/8527971a6705751208ee80856f86bc0aa927fa87)

**Comment by Narigo** [comment]
@augeneinblick if you want to contribute directly, you could also send a pull request - but you need to sign the Eclipse CLA before I would be able to merge it. See https://github.com/vert-x3/vertx-mysql-postgresql-client/blob/master/CONTRIBUTING.md

Otherwise, I see that I should do some changes to the tests anyways and could be able to implement those later today (after some sleep ;)).

**Comment by Narigo** [comment]
If someone could review #37 now, we can merge and close this issue :)
Thanks!

**Comment by ghulands** [comment]
What release will this be going into?

**Comment by Narigo** [comment]
Hopefully the next one :)

@vietj can we accelerate releases? I mean, would be nice to have releases that do not necessarily match a Vert.x release...?

**Comment by vietj** [comment]
what do you mean ? you want a new release of mysql based on Vert.x 3.2.1 ?
