### ISSUE TITLE
3.2.1 org.slf4j is missed by postgresql-async dep.

### ISSUE THREAD

**Issue by augeneinblick** [vert-x3/vertx-mysql-postgresql-client#38]
In a project which only uses following dependencies:
vertx-core, vertx-web and vertx-mysql-postgresql-client 

after upgrading from 3.2.0 to 3.2.1 
_postgresql-async_2.11_ is missing _org.slf4j_ due the exclusion in pom.xml.

[pom.xml](https://github.com/vert-x3/vertx-mysql-postgresql-client/blob/master/pom.xml#L63)

Quick solution is to add org.slf4j as a dependency in my project.

**Comment by cescoffier** [comment]
Hi,

This is expected. You need to add declare the version of `org.slf4j:slf4j-api` you want. This is made to avoid conflicts.
