### ISSUE TITLE
Mysql BIT(1) parse

### ISSUE THREAD

**Issue by leosilvadev** [vert-x3/vertx-mysql-postgresql-client#40]
Hi guys, I got an error here but I think probably is an error in asyn-mysql-async driver, not at the vertx bridge (I would like to be sure about it, so that's why I will post here)

Executing SELECT statements in Mysql when a column is of BIT(1) type brings me an invalid result: AQ== as String

Is there someone who got an issue like this?

[]'s

**Comment by leosilvadev** [comment]
Hi guys, I found the problem.
I got the same error trying to use mysql DECIMAL type, the error is that it brings scala BigDecimal, so it must be converted, I will fix at my app now, but I will study more the vertx-async bridge to see if there is a way to put this conversion easily.
Is there anyone who faced the same problem?

**Comment by leosilvadev** [comment]
I did a quick fix here, but I really don't know if it is the best one (fits for me now)

AsyncSQLConnectionImpl.java
```
private JsonArray rowToJsonArray(RowData data) {
    JsonArray array = new JsonArray();
    data.foreach(new AbstractFunction1<Object, Void>() {
      @Override
      public Void apply(Object value) {
        if (value == null) {
          array.addNull();
        } else if (value instanceof scala.math.BigDecimal) {
          array.add(((scala.math.BigDecimal) value).toDouble());
        } else if (value instanceof LocalDateTime) {
          array.add(value.toString());
        } else if (value instanceof LocalDate) {
          array.add(value.toString());
        } else if (value instanceof DateTime) {
          array.add(value.toString());
        } else if (value instanceof UUID) {
          array.add(value.toString());
        } else {
          array.add(value);
        }
        return null;
      }
    });
    return array;
  }
```

Any idea?
Thanks!

**Comment by Narigo** [comment]
@leosilvadev I tried to make a test for your issue to see if I can find a better fix. The current test I've added to `MySQLClientTest` would be:

```java
  @Test
  public void testBitFields(TestContext context) {
    Async async = context.async();
    client.getConnection(arConn -> {
      ensureSuccess(context, arConn);
      conn = arConn.result();
      conn.execute("DROP TABLE IF EXISTS test_table", arDrop -> {
        ensureSuccess(context, arDrop);
        conn.execute("CREATE TABLE test_table (id INT, some_bit BIT(1))", arCreate -> {
          ensureSuccess(context, arCreate);
          conn.execute("INSERT INTO test_table (id, some_bit) VALUES (1, 1),(2, 0),(3, 1)", arInsert -> {
            ensureSuccess(context, arInsert);
            conn.query("SELECT some_bit FROM test_table ORDER BY id", arQuery -> {
              ensureSuccess(context, arQuery);
              ResultSet res = arQuery.result();
              System.out.println(res.getRows().get(0));
              context.assertEquals(1, res.getRows().get(0).getBoolean("some_bit"));
              context.assertEquals(0, res.getResults().get(1).getInteger(0));
              context.assertEquals(1, res.getRows().get(2).getDouble("some_bit"));
              async.complete();
            });
          });
        });
      });
    });
  }
```

...but the fix you proposed doesn't work with this. What's the code you're testing?

**Comment by leosilvadev** [comment]
@Narigo, no, the fix I proposed is about Mysql DECIMAL results, I will check out the BIT response (must be something similar)

**Comment by leosilvadev** [comment]
Try to change the table column from BIT(1) to DECIMAL(10,2)

**Comment by leosilvadev** [comment]
I tested here, the problemn happens (in DECIMAL case) exactly when the value is 0.0

**Comment by leosilvadev** [comment]
The BIT(1) problem brings me a byte[1], with 0 or 1 value

**Comment by Narigo** [comment]
@leosilvadev if you use double values, you might loose information that you had in `BigDecimal`. Imagine big numbers like this:

`new BigDecimal("43210987654321098765432109876543210987654321098765432109871.123451")`

This is a `DECIMAL(65,6)`. If the information would stay, the following assertion should hold true, but doesn't:

```java
BigDecimal bd = new BigDecimal("43210987654321098765432109876543210987654321098765432109871.123451");
context.assertEquals(bd, new BigDecimal(bd.doubleValue()));
```

So the only way I can think of to mitigate this problem is to convert `BigDecimal` into `String` and have the user parse the result into the desired type again (as JSON doesn't allow those big numbers).

@pmlopes maybe you can think of something better?

...and after looking into it a bit more, I doubt that the issue with `DECIMAL` and `BIT(1)` is the same. At least I don't get the same errors here.

**Comment by leosilvadev** [comment]
@Narigo yes, I faced this problems many times, that's why I think it really not the best solution
About the String I thought about this too, since the we can create BigDecimal with String constructor without loose data.

About BIT(1), it returns a byte[] with only one value (0 or 1), but it's a bit complicated because it's exclusive for BIT(1), BIT(2) is a differente answer... I was thinking that, even when we fix this issues, perhaps would be good to provide a way to use an abstract rowParser, to modify any specific logic, does it sounds bad?

**Comment by Narigo** [comment]
See #41 for the first part. About the second (BIT columns), I'll open an issue at the underlying driver's repository shortly.

**Comment by Narigo** [comment]
After the new information from Mauricio, I've added tests to show usage for `BIT` and `BYTEA` columns in PR #42.

@leosilvadev I'm waiting for a review of PR #41 that should fix the `DECIMAL` issue.
I guess the `BIT` column is correct as it works. Maybe we could add a BIT(9) that would return a `byte[2]` to make it clear?

**Comment by leosilvadev** [comment]
@Narigo , thanks, I'll be waiting for the BigDecimal solution.
About BIT, I will check out here a little bit more.

**Comment by Narigo** [comment]
@leosilvadev is anything left to do here or can I close this issue now? BigDecimal will be converted into Strings to not loose information through JSON. What about the `BIT` thing, is there something I'm missing right now?

**Comment by leosilvadev** [comment]
@Narigo nothing for now, I think it's better to close it for now, when I got some time I will check the BIT problem and if needed I can open another issue
