### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by Narigo** [vert-x3/vertx-mysql-postgresql-client#43]
It can be possible to use SSL encrypted connections with the newest driver version (0.2.19). I'll upgrade to that version shortly (that will fix another bug regarding `NUMERIC` columns) and then we are able to add SSL support.

**Comment by onesse** [comment]
Hi,
You speak about the SSL support but I don't see how to enable it. I checked on forums and vertx website but there is no really clear explanations. Writing a small paragraph would be great :)
Regards

**Comment by Narigo** [comment]
It's not supported yet. The driver could do it, but we need to add an API to use SSL in our client here as well.

**Comment by onesse** [comment]
Ok, thanks for your response. Do you have any idea when this feature will be available ?

**Comment by Mart-Bogdan** [comment]
I've just encountered same problem.
It's seems quite straight forward to add support, will make PR soon.

It's impossible to run on Heroku w/o SSL :c

**Comment by bkimbrou** [comment]
Is there any chance that https://github.com/vert-x3/vertx-mysql-postgresql-client/pull/88 will be merged in any time soon?

**Comment by vietj** [comment]
can we close this issue then ?

**Comment by Narigo** [comment]
Yes!

**Comment by jbkoh** [comment]
I know this is closed and the PR has been merged. When will the new version be released with this feature?

**Comment by vietj** [comment]
@jbkoh soon hopefully, it's being staged atm

**Comment by jbkoh** [comment]
Thanks. I was wondering if I should start from java.sql directly or this.

**Comment by vietj** [comment]
what are you aiming for ?

**Comment by jbkoh** [comment]
Just want to make a Vertx service communicate with (or query to) a remote PostgreSQL with SSL enabled. Is there other solutions for this?

**Comment by vietj** [comment]
you can also check https://github.com/vietj/reactive-pg-client

**Comment by jbkoh** [comment]
@vietj Thanks for the pointer. I see that you are the main author of both this and that. Could you briefly introduce what the difference is?

**Comment by vietj** [comment]
the client has been developed to be a client for postgres with some specificities: it implements a bit more than the actual vertx-mysql-postgresql-client like batching or notifications.

**Comment by jbkoh** [comment]
Thanks for the prompt response. I will stick to the later. Thank you.
