### ISSUE TITLE
Bug handling NUMERIC in underlying postgresql driver

### ISSUE THREAD

**Issue by alexvetter** [vert-x3/vertx-mysql-postgresql-client#47]
We have a problem regarding the handling of `NUMERIC` columns. It's a bug in the underlying postgresql driver. @Narigo already did some research (https://github.com/mauricio/postgresql-async/pull/164) and based on that the bug was fixed.

> When using NUMERIC columns, updating them with an integer value at first and updating it with a floating number later, an exception is thrown.

The fix is included in the current release of the driver (0.2.19). @Narigo also did an PR for upgrading the postgresql driver (https://github.com/vert-x3/vertx-mysql-postgresql-client/pull/45).

It would be great to have an bugfix release of the mysql-postgresql-client.

**Comment by jan-zajic** [comment]
please someone close this issue as fixed with #45, which is merged
