### ISSUE TITLE
SQL error throws an NullPointerException at version 3.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by leosilvadev** [vert-x3/vertx-mysql-postgresql-client#49]
I got a NullPointerException and was just checking out why, the problem happens when the SQL execute has an error (example select an invalid column).
The NullPointer happens at:
- MySQLConnectionImpl: line 21

**Comment by Narigo** [comment]
See https://github.com/vert-x3/vertx-mysql-postgresql-client/pull/52
