### ISSUE TITLE
slf4j not found 

### ISSUE THREAD

**Issue by ivanpopelyshev** [vert-x3/vertx-mysql-postgresql-client#56]
I have only that in my dependencies:

```groovy
    compile 'io.vertx:vertx-web:3.3.3'
    compile 'io.vertx:vertx-mysql-postgresql-client:3.3.3'
```

It seems I need extra logger libs. This is what I see while trying get the connection:

```txt
INFO: creating a connection went wrong
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.mauricio.async.db.util.Log$.getByName(Log.scala:27)
	at com.github.mauricio.async.db.postgresql.column.PostgreSQLIntervalEncoderDecoder$.<init>(PostgreSQLIntervalEncoderDecoder.scala:28)
	at com.github.mauricio.async.db.postgresql.column.PostgreSQLIntervalEncoderDecoder$.<clinit>(PostgreSQLIntervalEncoderDecoder.scala)
```

What do I have to add in my dependencies, and how to initialize it?

**Comment by ivanpopelyshev** [comment]
OK, more info: it happens only when I try to debug in Intellij Idea. I'll close it for now

**Comment by indiealexh** [comment]
For others looking for a solution to this, simply include the slf4j api version you want in your dependencies.

e.g.

```xml
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.22</version>
</dependency>
```

**Comment by sinri** [comment]
This issue could be found even in 3.8.3, and the solution given by @indiealexh is still available.
