### ISSUE TITLE
NoSuchMethodError in ResultSet

### ISSUE THREAD

**Issue by remi128** [vert-x3/vertx-mysql-postgresql-client#63]
using the 3.4.0-SNAPSHOT:
Method AsyncSqlConnectionImpl.queryResultToResultSet in line 302 crashes with NoSuchMethodError, cause the constructor of ResultSet in sql-commons does no more exists. The existing one is now 
public ResultSet(List<String> columnNames, List<JsonArray> results, ResultSet next)

**Comment by pmlopes** [comment]
PR #62 fixes it. It is waiting reviews.

**Comment by Narigo** [comment]
As PR #62 is merged, this should be done.
