### ISSUE TITLE
java.lang.IllegalStateException: Illegal type in JsonObject: class scala.collection.mutable.ArrayBuffer

### ISSUE THREAD

**Issue by ukr15** [vert-x3/vertx-mysql-postgresql-client#76]
Hi there,
i tried to read a Postgres database table with array attributes and get an
java.lang.IllegalStateException: Illegal type in JsonObject: class scala.collection.mutable.ArrayBuffer error 
`conn.result().queryStream("SELECT * FROM person_pps001_3 LIMIT 1000000", stream->{
						 if(stream.failed()){
							 System.out.println("Stream: "+stream.cause());
							 return;
						 } ....`

**Comment by tsegismont** [comment]
Duplicates #73
