### ISSUE TITLE
When will the batch and batchWithParams be implemented?

### ISSUE THREAD

**Issue by tramchamploo** [vert-x3/vertx-mysql-postgresql-client#83]
Really eager to use this feature, it is hard to implement this asynchronously?

**Comment by pmlopes** [comment]
The sql options pr does implement it. It's quite some big pr and all reviews are welcome.

**Comment by tramchamploo** [comment]
When is it expected to be merged?

**Comment by pmlopes** [comment]
the top level pr is approved now it is a matter of getting the implementations reviewed, so all eyes will help.
