### ISSUE TITLE
Provide MySQLClient with create method that accepts DataSource

### ISSUE THREAD

**Issue by juanavelez** [vert-x3/vertx-mysql-postgresql-client#96]
Currently there is no MySQLClient create method that creates an instance using a DataSource. This should be similar to what exists in [https://github.com/vert-x3/vertx-jdbc-client/blob/master/src/main/java/io/vertx/ext/jdbc/JDBCClient.java](url)

**Comment by tsegismont** [comment]
Would you like to contribute this?

**Comment by juanavelez** [comment]
Yes, I will try to work on it this weekend
    On Wednesday, December 20, 2017, 1:52:22 PM PST, Thomas Segismont <notifications@github.com> wrote:  
 
 
Would you like to contribute this?

**Comment by juanavelez** [comment]
@tsegismont Please correct me if I am wrong, but It looks like it is not possible to implement a `MySQLClient.create(io.vertx.core.Vertx, javax.sql.DataSource)` as the underlying library (mysql-async) does not support a DataSource object but a Configuration object which can't be populated using a DataSource instance.

**Comment by Narigo** [comment]
Yes, a `DataSource` would only give us a connection based on the JDBC API, which is not what we can use here. I'm closing this as the underlying driver needs to create its own (async) connection.
